[package]
name = "settings"
version = "0.1.0"
edition = "2021"

[dependencies]
regex = { version = "1.11.1" }
serde = "1.0.217"
serde_derive = "1.0.217"
serde_yaml = "0.9.34"
thiserror = { workspace = true }
